FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app
COPY publish/ .

USER $APP_UID

EXPOSE 8580
ENV ASPNETCORE_URLS=http://+:8580
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "BecauseImClever.Server.dll"]
